In [5]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
# feature Scaling - KNN
# Normalazation - Standardzation

In [9]:
df = pd.read_csv("datas/Advertising.csv")

In [80]:
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [82]:
X = df.drop('Sales' , axis=1)
X = X.drop('Unnamed: 0' , axis=1)
X

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [84]:
y = df['Sales']

In [86]:
from sklearn.preprocessing import PolynomialFeatures

In [88]:
poly_converter = PolynomialFeatures(degree=3 , include_bias=False)

In [90]:
poly_features = poly_converter.fit_transform(X)

In [92]:
from sklearn.model_selection import train_test_split

In [94]:
X_train , X_test , y_train , y_test = train_test_split(
    poly_features , 
    y , 
    test_size=0.3,
    random_state=101
)

In [96]:
from sklearn.preprocessing import StandardScaler

In [98]:
scaler = StandardScaler()

In [100]:
scaler.fit(X_train)

StandardScaler()

In [102]:
X_train_s = scaler.transform(X_train)

In [104]:
X_test_s = scaler.transform(X_test)

In [106]:
X_train_s[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [108]:
X_train_s[:, 0].std()

1.0

In [110]:
# find best alpha (a;pha helps us againts overfitting and underfitting)
from sklearn.linear_model import RidgeCV

In [112]:
ridge_cv_model = RidgeCV(alphas= (0.1 , 1.0 , 11.0) , scoring="neg_mean_absolute_error")

In [114]:
ridge_cv_model.fit(X_train_s , y_train)

RidgeCV(alphas=(0.1, 1.0, 11.0), scoring='neg_mean_absolute_error')

In [116]:
ridge_cv_model.alpha_

0.1

In [118]:
test_predictions = ridge_cv_model.predict(X_test_s)

In [120]:
from sklearn.metrics import mean_absolute_error , mean_squared_error

In [124]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test , test_predictions)
RMSE = np.sqrt(MSE)

In [129]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [133]:
# lasso Regrassion

In [139]:
from sklearn.linear_model import LassoCV

In [151]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100 , cv=10)

In [153]:
lasso_cv_model.fit(X_train_s , y_train)

LassoCV(cv=10, eps=0.1)

In [155]:
lasso_cv_model.alpha_

0.4943070909225828

In [157]:
test_predection = lasso_cv_model.predict(X_test_s)

In [159]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [161]:
# elastic Net

In [163]:
from sklearn.linear_model import ElasticNetCV

In [165]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5 , .7 ,  .9 , .95 , .99 , 1], tol=0.01)

In [167]:
elastic_model.fit(X_train_s, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [169]:
elastic_model.l1_ratio_

1.0

In [171]:
test_prediction = elastic_model.predict(X_test_s)

In [173]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])

In [175]:
elastic_model.alpha_

0.004943070909225827