In [ ]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
# now we want to select our data
from google.colab import files

my_dataset = files.upload()

In [ ]:
df = pd.read_csv('lebron_shot_data.csv')

In [ ]:
df.info()

In [ ]:
df.head()

,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,EVENT_TYPE,...,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM,SEASON
0,20300014,20,2544,LeBron James,1610612739,Cleveland Cavaliers,1,8,56,Made Shot,...,8-16 ft.,15,158,0,1,1,20031029,SAC,CLE,2003-04
1,20300014,28,2544,LeBron James,1610612739,Cleveland Cavaliers,1,7,44,Made Shot,...,8-16 ft.,13,-131,2,1,1,20031029,SAC,CLE,2003-04
2,20300014,35,2544,LeBron James,1610612739,Cleveland Cavaliers,1,7,1,Made Shot,...,16-24 ft.,16,163,5,1,1,20031029,SAC,CLE,2003-04
3,20300014,39,2544,LeBron James,1610612739,Cleveland Cavaliers,1,6,29,Missed Shot,...,8-16 ft.,14,-118,92,1,0,20031029,SAC,CLE,2003-04
4,20300014,54,2544,LeBron James,1610612739,Cleveland Cavaliers,1,4,48,Made Shot,...,Less Than 8 ft.,5,54,22,1,1,20031029,SAC,CLE,2003-04

In [ ]:
df.describe()

,GAME_ID,GAME_EVENT_ID,PLAYER_ID,TEAM_ID,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE
count,2.931100e+04,29311.000000,29311.0,2.931100e+04,29311.000000,29311.000000,29311.000000,29311.000000,29311.000000,29311.000000,29311.0,29311.000000,2.931100e+04
mean,2.122812e+07,275.322882,2544.0,1.610613e+09,2.513561,5.044352,28.290676,11.708744,-9.263075,80.572208,1.0,0.506192,2.012953e+07
std,6.048328e+05,172.893844,0.0,4.175265e+00,1.152725,3.458327,17.593051,10.336964,102.846589,91.731562,0.0,0.499970,6.033555e+04
min,2.030001e+07,1.000000,2544.0,1.610613e+09,1.000000,0.000000,0.000000,0.000000,-248.000000,-44.000000,1.0,0.000000,2.003103e+07
25%,2.070056e+07,116.000000,2544.0,1.610613e+09,1.000000,2.000000,13.000000,1.000000,-68.000000,6.000000,1.0,0.000000,2.008012e+07
50%,2.120051e+07,275.000000,2544.0,1.610613e+09,3.000000,5.000000,28.000000,11.000000,0.000000,33.000000,1.0,1.000000,2.013011e+07
75%,2.170095e+07,401.000000,2544.0,1.610613e+09,3.000000,8.000000,43.000000,22.000000,23.000000,156.000000,1.0,1.000000,2.018030e+07
max,2.230123e+07,833.000000,2544.0,1.610613e+09,7.000000,12.000000,59.000000,86.000000,249.000000,845.000000,1.0,1.000000,2.024041e+07

In [ ]:
# projects 1 - each year -> how many 3P Jmaes mades
# what we need ? we need ich game ID and all 3P first with type of
# made -> is maded or not

In [ ]:
# copy datasets and we create our new fetures

firstprojectsdataset = df[[
    'GAME_EVENT_ID' , 'TEAM_ID' , 'EVENT_TYPE' , 'ACTION_TYPE' ,'PERIOD','MINUTES_REMAINING' , 'SEASON'
    ]]

firstprojectsdataset.head()

,GAME_EVENT_ID,TEAM_ID,EVENT_TYPE,ACTION_TYPE,PERIOD,MINUTES_REMAINING,SEASON
0,20,1610612739,Made Shot,Jump Shot,1,8,2003-04
1,28,1610612739,Made Shot,Jump Shot,1,7,2003-04
2,35,1610612739,Made Shot,Fadeaway Jump Shot,1,7,2003-04
3,39,1610612739,Missed Shot,Jump Shot,1,6,2003-04
4,54,1610612739,Made Shot,Running Jump Shot,1,4,2003-04

In [ ]:
# time to explan what we want
# 1 - we want calculate all successed three point fisrt

firstprojectsdataset = df[[
    'GAME_EVENT_ID' , 'TEAM_ID' , 'EVENT_TYPE' , 'ACTION_TYPE' ,'PERIOD','MINUTES_REMAINING' , 'SEASON'
    ]]

In [ ]:
# now we cooect all 3P in collect

all_3p_made = firs